//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XB1ControllerBatteryIndicator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XB1ControllerBatteryIndicator.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string BatteryLevel_Empty {
            get {
                return ResourceManager.GetString("BatteryLevel_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string BatteryLevel_Full {
            get {
                return ResourceManager.GetString("BatteryLevel_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string BatteryLevel_Low {
            get {
                return ResourceManager.GetString("BatteryLevel_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string BatteryLevel_Medium {
            get {
                return ResourceManager.GetString("BatteryLevel_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string ContextMenu_AutoStart {
            get {
                return ResourceManager.GetString("ContextMenu_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ContextMenu_Language {
            get {
                return ResourceManager.GetString("ContextMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty battery warning sound.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound_Enabled {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on loop.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound_Loop_Enabled {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound_Loop_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version on start.
        /// </summary>
        public static string ContextMenu_UpdateCheck {
            get {
                return ResourceManager.GetString("ContextMenu_UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string ControllerIndex_Four {
            get {
                return ResourceManager.GetString("ControllerIndex_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string ControllerIndex_One {
            get {
                return ResourceManager.GetString("ControllerIndex_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string ControllerIndex_Three {
            get {
                return ResourceManager.GetString("ControllerIndex_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string ControllerIndex_Two {
            get {
                return ResourceManager.GetString("ControllerIndex_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} is available. Do you want to open the Homepage?.
        /// </summary>
        public static string NewVersionAvailable_Body {
            get {
                return ResourceManager.GetString("NewVersionAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVersionAvailable_Title {
            get {
                return ResourceManager.GetString("NewVersionAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut up!.
        /// </summary>
        public static string Toast_Dismiss {
            get {
                return ResourceManager.GetString("Toast_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery of controller {0} is (almost) empty..
        /// </summary>
        public static string Toast_Text {
            get {
                return ResourceManager.GetString("Toast_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click on the Button to stop the reappearing of this warning.).
        /// </summary>
        public static string Toast_Text2 {
            get {
                return ResourceManager.GetString("Toast_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} low battery warning.
        /// </summary>
        public static string Toast_Title {
            get {
                return ResourceManager.GetString("Toast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controller detected.
        /// </summary>
        public static string ToolTip_NoController {
            get {
                return ResourceManager.GetString("ToolTip_NoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Unknown.
        /// </summary>
        public static string ToolTip_Unknown {
            get {
                return ResourceManager.GetString("ToolTip_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Found but still waiting for battery data....
        /// </summary>
        public static string ToolTip_WaitingForData {
            get {
                return ResourceManager.GetString("ToolTip_WaitingForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Wired.
        /// </summary>
        public static string ToolTip_Wired {
            get {
                return ResourceManager.GetString("ToolTip_Wired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Battery level: {1}.
        /// </summary>
        public static string ToolTip_Wireless {
            get {
                return ResourceManager.GetString("ToolTip_Wireless", resourceCulture);
            }
        }
    }
}
